version: '2.4'

services: 
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
  api:
    container_name: apibackend
    build: ./planb_backend
    restart: "no"
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 planB_backend.wsgi:application"
    expose: 
      - '8000'
    volumes: 
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
    - planb_backend/.env
    depends_on: 
      - db
        # condition: service_healthy
  db:
    image: mysql:latest
    # container_name: mysql
    # build: ./mysql
    ports: 
      - 3306:3306
    volumes: 
      - db_data:/var/lib/mysql
      # - /code/mysqld:/var/run/mysqld
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:planBdb
      - MYSQL_USER:planBuser
      - MYSQL_PASSWORD:planB_pass_1399
      - ALLOW_EMPTY_PASSWORD:yes
      - MYSQL_AUTHENTICATION_PLUGIN:mysql_native_password
    # healthcheck:
    #   - test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
    #   - timeout: 20s
    #   - retries: 10



volumes: 
  static_volume:
  media_volume:
  db_data: